apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: cert-manager
    repoURL: hhttps://charts.jetstack.io
    targetRevision: v1.1.0
    helm:
      values: |
        installCRDs: true
  destination:
    name: do-nyc3-k8s-beet-infra 
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true