apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-operator
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAyL8VYXGm4OrrS3uIN6HsmgC88UBPf9Lb1T+mVUWgf1sUCCb1lSyEO+Y+AT5pczA23ODJalAQY/hdkE3cO9OS2TnlOhS5DdVYChlQwb5jm8+lkddwslAtrVD0B3G3usX8XKqTPRGtEWEHpPz4GwZoNV8eRw3IOV8mzKH8WqJBKwOyVQfUpbVGSEnWa0dXhN70ZRgu08eaavFQb19MOyzpn1XTxTnm/F6r/wpelsHz23HuqZy2RiDN1h5njW7U/zRGC/jodUrfB3QMuvs5spvCUClEvk4oyUB8O66bb0USKluKSQVfM0o+WRI92BokznznChQ/ptmfKetxmJmYrXfEU3hsQYhfoARoDpg5XS7BaRn+hjZ4v/nfZgCi5/0qeIS5MRJqRoYxoQ8yl4Dhiz0c1xGOjL8a8QfvmD5p86wvozVaRaWMWOifUS7bHSpPLIxVLGBlLIO7d5U+vr3YklRxLhZjHGFokf57Vi0wWRyXgfv7mqvTGUUY0oS8QX1V26CjfMGUXxyg7BdoAiM7r8HUXJpc8XVQxnFxbldBjNrPs+YlDGVIMOiK1T4lO0DOsQPDvM4SHy70B0Jh+5Zq+Fjx1HjKXWeLdEM9cn+L8dgR31N902Sijr1aIwk8mvpCKZo3YTSCqwIysYmAv6sl7xrWL2fZi7G1xeMgZnlUhMnVGUMSJ0eVMN+o6+1STDqrLJCrcbZ6JRlED4LpUNkBh09E3OpRlJA==
    AWS_SECRET_ACCESS_KEY: AgDnyXlA1WWG+lBuqOTpP56y9tvK01Ltvi5tJGItJ9YWYbZUZQSVQvQdwBDqXO5p4hAudQQDWyON+jOEe5WQuP8uj1I9UtOG8kBouKU/wV9PVIu9RnE3jCsICqYCI9d6dFxRYy7fUOswpsIv1YeTyXbdmWJEQVxXFvnqWikwRX9c61iMzuB9u33FK+ctMp9r79xPhb9dhl8TUtRCxpkUltF+CRc6Z+Q7KhtyKS++ySwJ6sMk6wDgXO0ziMWqxgg3DwXzLZWVIxwbBNE8tbhGaz0SpCmYBXGqOIeMOOlPjBH4lIs2wm97HS35xZbC2kTxugGeYem4xRw0i5aEqwVrSaErhGhpUf9/G6DN33B2v1aX+C+20HBCzqyR8xoU4dCXzYfDvTH/0u+wnQh1TnR+q14R+Fe9qSHTfhPAo/rHJW3Nxb4slzAswaoV05IqX2p3o6Whlbhcs5HB27e4jHs4HEFjT12MOxoiqESrFcpDyp+fjWSdKnoFSXKIDhDTDnnV7RcBmSbLQq7Wxso7JY9wcgM0RbFCPFCHPjbMdVVSm+/K1NHuU9vnwMMpFz0Avm/eA2BN5ghTWE3YIb02feZ7qEegKfvMiwFU9nfMfrXWnTIhkyCbust3WdFXdLWLKDTUrzosKs8A4/r+v0181ww7TQaCkw2Snz1alrGsTJA9/HVN2+yWHSmj5S0/2+Y6HnOOz9zY7v1juMhZW6iPp4KBnh8nGbPgLvZAKtMmwqUwgxON8EMwUxrMlLX0CuDz
  template:
    metadata:
      creationTimestamp: null
      name: postgres-operator
      namespace: default

