apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digitalocean-dns
  namespace: cert-manager
spec:
  encryptedData:
    access-token: AgARo0MmaabgREbZKXEYOEejNeSHdrOlWMBiOBlt6cxi3W77L3MhkUViJBGcJcf01IMHkGP38AET7PX9lpDO4FRbzzSzO8NpICCBHNExlcKDfRoDLNSN6jBxuiQhkktg31wdj5bU5ytcK1YQkPH9jhiytXsd6Y+2mwoSu92v9Xco5g7py2KFYhZBZBPKgj0umCOWuPf2/oudcIS5hTZJQyTpaU2pCr6cPNbyRhzIIhRsZYWWlbccDuDwsKfJfyTVLivKOe0+uRCrjKxbx74G3zCPn4XDqKAyCkw0Sz+TJ6UbR/coRFr7LrkCyaWOiChkCEia6idPT6xljV7mgS6EEuL3eACDBpKgxvxCGsf6xTNWwrPfQvCkodHitcMf+Tdr97qfMQC4K7Rs7SXvzZhIEBTQkLYvDI6UZuN9he/bhmTw/Ic44X2NUJsY+ZMb+VbWqqhfxKfegu/7oChsqoVpiXU6mkjwi2SDi+GBCiIAcYaOrxyWvVON41GDNw139iZg7q46NoHuAYd4GCx6tQJ649ebcaR+5IycKKLPBLwdBBB4wyJWc8xWGz7hLc//1bYnVBtdXA7huFRAZq9FAca/2CfEnMGhIQLI9e2vUp/14KYi62YM7zAd6jEOGKsbh8+wBCiMT3BPBmOOAx/Nw+S6NqpPLehNknx1NTHEjyN9b3u+cGBosqGK2BMAX8uhuGMRgKd+kRxAN+P9kFKOHOpHSJRDpjZVHs+KpZqcXtYnQOsilni+/CzpEzzjA3re76WMYqrMEXntc2I9Xz0GB8U8ms7Y
  template:
    metadata:
      creationTimestamp: null
      name: digitalocean-dns
      namespace: cert-manager

